-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-11-21 01:52:21 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cards (
    card_id      INTEGER NOT NULL,
    card_title   VARCHAR2(4000) NOT NULL,
    tag          VARCHAR2(4000),
    name         VARCHAR2(4000) NOT NULL,
    company      VARCHAR2(4000) NOT NULL,
    position     VARCHAR2(4000) NOT NULL,
    "User"       VARCHAR2(4000) NOT NULL,
    column_8     unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
    ,
    user_user_id INTEGER NOT NULL,
    tags_tag_id  INTEGER NOT NULL
);

ALTER TABLE cards ADD CONSTRAINT cards_pk PRIMARY KEY ( card_id );

CREATE TABLE tags (
    tag_id   INTEGER NOT NULL,
    tag_name VARCHAR2(4000) NOT NULL
);

ALTER TABLE tags ADD CONSTRAINT tags_pk PRIMARY KEY ( tag_id );

CREATE TABLE "User" (
    user_id       INTEGER NOT NULL,
    user_password VARCHAR2(4000) NOT NULL,
    user_name     VARCHAR2(4000) NOT NULL,
    email         VARCHAR2(4000)
);

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( user_id );

ALTER TABLE cards
    ADD CONSTRAINT cards_tags_fk FOREIGN KEY ( tags_tag_id )
        REFERENCES tags ( tag_id );

ALTER TABLE cards
    ADD CONSTRAINT cards_user_fk FOREIGN KEY ( user_user_id )
        REFERENCES "User" ( user_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
