-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-11-29 11:25:30 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE card (
    cardid        SERIAL NOT NULL,
    card_name     VARCHAR(100) NOT NULL,
    card_position VARCHAR(100) NOT NULL,
    card_company  VARCHAR(100) NOT NULL,
    user_userid   INTEGER NOT NULL,
    tag_tagid     INTEGER NOT NULL
);

CREATE UNIQUE INDEX card__idx ON
    card (
        tag_tagid
    ASC );

ALTER TABLE card ADD CONSTRAINT card_pk PRIMARY KEY ( cardid );

CREATE TABLE tag (
    tagid   SERIAL NOT NULL,
    tagname VARCHAR(100) NOT NULL
    
);

-- Error - Index tag__IDX has no columns

ALTER TABLE tag ADD CONSTRAINT tag_pk PRIMARY KEY ( tagid );

CREATE TABLE "user" (
    userid   SERIAL NOT NULL,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

ALTER TABLE "user" ADD CONSTRAINT user_pk PRIMARY KEY ( userid );

ALTER TABLE card
    ADD CONSTRAINT card_tag_fk FOREIGN KEY ( tag_tagid )
        REFERENCES tag ( tagid );

ALTER TABLE card
    ADD CONSTRAINT card_user_fk FOREIGN KEY ( user_userid )
        REFERENCES "user" ( userid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             1
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
